server:
  port: 8088
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  h2:
    console:
      enabled: true
    settings:
      web-allow-others: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


#  security:
#    user:
#      name: username
#      password: passw0rd

management:
  endpoints:
    web:
      exposure:
        include: "*"